[pytest]

# =========================
# TEST DISCOVERY
# =========================
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# =========================
# OUTPUT / LOGGING
# =========================
addopts = -s -v

# =========================
# ALLURE REPORTING
# =========================
--alluredir=allure-results

